name: bloom-ci

on: [push, pull_request]

jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
          python: [2.7, 3.5, 3.6, 3.7, 3.8]
          exclude:
          - os: ubuntu-16.04
            python: 3.6
          - os: ubuntu-16.04
            python: 3.7
          - os: ubuntu-16.04
            python: 3.8
          - os: ubuntu-18.04
            python: 3.5
          - os: macos-latest
            python: 3.5
          - os: macos-latest
            python: 3.6
      name: bloom tests
      runs-on: ${{matrix.os}}

      steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install PyYAML argparse empy rosdep vcstools catkin-pkg python-dateutil
          python -m pip install nose coverage pep8
      - name: Configure rosdep
        run: |
          which rosdep
          sudo `which rosdep` init
          `which rosdep` update
      - name: Run tests
        run: |
          BLOOM_VERBOSE=1 python setup.py nosetests -s --tests test
